# Не трогайте, а то конфиг будет автоматически считаться устаревшим
version-config: 1.0
# Права: itemedit.admin
lore:
  enabled: true # Будет ли вообще работать проверка
  characters-per-line: 30 # Ограничение символов
# Файл с большой базой фраз для проверки плагина
# !!!Для работы требуется разовый доступ к интернету!!!
words: false
# Символ с которого будет перенос на след.строку
newline-char: '&r'
# Символы которые не будут учитываться регистром
char-no-length: ''
# Действия после которых будет проверяться и изменяться предмет
inventory-open: true
inventory-close: true
inventory-drop: true
player-command: true